### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#1]
## User Story
As a user, when I navigate to your site, I should see a navbar.

## AC
**Given** A user navigates to your page
**Then** they should see a navbar
**And** it should have an application logo
**And** it should have an input field
**And** it should have a clear button
**And** it should remain at the top of the screen if the page scrolls

## Dev Notes
* Logo will be made by Laura
* Input fields and buttons from bootstrap (see below)
* Bootstrap navbar below
* Fontawesome icons for dark theme and text size below.

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/66880065-c322ba80-ef86-11e9-90b6-0aeb453d9da3.png)

**Comment by LaCollins** [comment]
Font Awesome Moon: `<i class="fas fa-cloud-moon"></i>`
Font Awesome Text Resize Icon: `<i class="fas fa-text-height"></i>`
.

**Comment by LaCollins** [comment]
Bootstrap Form for text box: `<input class="form-control" type="text" placeholder="Default input">`

**Comment by LaCollins** [comment]
Clear Button - use Outline: https://getbootstrap.com/docs/4.0/components/buttons/#outline-buttons

**Comment by LaCollins** [comment]
Button for Submit: https://getbootstrap.com/docs/4.0/components/buttons/#examples

**Comment by LaCollins** [comment]
Use Bootstrap Flex to make Name form shorter: https://getbootstrap.com/docs/4.0/components/forms/#form-row

**Comment by LaCollins** [comment]
Bootstrap Navbar: https://getbootstrap.com/docs/4.0/components/navbar/

**Comment by LaCollins** [comment]
Sticky CSS:   
`position: fixed;
  top: 0;
  width: 100%;`
