### ISSUE TITLE
Gif Selector

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#12]
# User Story
**Giphy Api**: Go to https://developers.giphy.com/ and set yourself up with a login and create an app (you can enter whatever information in those fields). You will be using the Search endpoint.

- Near my message input field, I would like to be able to click on a `Add Gif` button. When I click on that button, a text field should show up in some way so that I can search for a gif.
- After searching, I would like to see some options of gifs to choose. I choose a gif by clicking on the image. The options should then disappear and I should see some indicator that I selected a gif for my message. 
- When I click send on my message, the gif should appear in the dom with the message that I sent. If there was no text in the chat field, the message should only contain the gif.

# A/C
**When** the user clicks 'add gif'
**then** a modal pops up with a search bar and submit button
**When** the user enters a search
**then** 10 results populate in the modal with a 'choose' & 'cancel' button at the bottom
**when** the user selects a gif and clicks choose
**then** the gif is added to their message
**or** clicking cancel returns the user to the gif search bar

# Dev Notes
* add 'gif' key to seed data objects
* use bootstrap modal
* loop through API results and pull 10 giphy IDs into an array
* loop through the giphyID array to print the options in the modal
* add click function to gif results that highlights the chosen gif (only one at a time)
* click function on choose returns the id from the highlighted gif 
* toggle add gif/gif added button to show when attached
* import gif into addMsg.js and include in new object build
* print gif in separate div from message on displayMsg

**Comment by aclai4067** [comment]
npm giphy API install: https://www.npmjs.com/package/giphy-api

**Comment by aclai4067** [comment]
example giphy API search in JS: https://www.youtube.com/watch?v=mj8_w11MvH8

**Comment by aclai4067** [comment]
bootstrap modal: https://getbootstrap.com/docs/4.3/components/modal/

**Comment by aclai4067** [comment]
giphy beta key `YdazyFlfiiIEP6hKfrZQMtgytf2CMG9A`
