### ISSUE TITLE
Add Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#13]
## User Story
As a user, I should be able to add messages by clicking enter.

## AC
**Given** A user navigates to your page
**Then** they type in the input field
**And** when they hit enter a new message should be created
**And** the message should show up in the new chat window

## Dev Notes
- `.shift` the contents of the input field to the `messages` array along with the current time and the name in the name field, and setting initial upvotes and downvotes to 0.  Reprint `messages` to the chat window and clear the message input field (but not the name).
- To avoid a circular dependency, the function that displays `messages` will take in an array parameter, and will be imported into this module so that the new `messages` array can be printed to the page using the same function as prints the initial messages.

**Comment by LaCollins** [comment]
Button should say "Enter" not "Submit"

![image](https://user-images.githubusercontent.com/51382883/66879959-53143480-ef86-11e9-93f5-c9d79b34fcf9.png)

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/66879970-61625080-ef86-11e9-9130-0a13232f4708.png)
