### ISSUE TITLE
Clear Messages

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#14]
## User Story
As a user, when I have messages, I should be able to clear them out with a single button.

As a user, when I DON'T have messages, I should not be able to click the clear button

## AC
**Given** A user navigates to your page
**Then** they see a bunch of messages
**And** they click the clear button
**And** the chat history should get cleared out

**Given** A user navigates to your page
**And** they see no messages
**Then** the clear button should be disabled.

## Dev Notes
* When the clear button is pressed, the message array should be cleared.
* If the array is empty, then the "clear" button is disabled.
* If the array has data, enable button
* Use JQuery documentation below for reference

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/66880681-915f2300-ef89-11e9-9a91-cc50481a974e.png)

**Comment by LaCollins** [comment]
https://www.mkyong.com/jquery/how-to-disable-submit-button-after-clicked-with-jquery/
