### ISSUE TITLE
Delete Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#16]
## User Story
As a user I should be able to delete messages.

If you are doing multiple users you should only be able to delete **your** messages

## AC
**Given** A message on your page
**Then** there should be a delete button for each message (that belongs to your user)
**And** when the button is pushed the message should no longer exist

## Dev Notes
* Assign an ID that corresponds to the array location
* When the delete button is pressed, pull ID and use `splice()` to remove it from the array and rebuild the array.

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/66880622-5361ff00-ef89-11e9-8dd6-f69c933139d3.png)

**Comment by LaCollins** [comment]
Use expel button method: 
https://github.com/LaCollins/sorting-hat/blob/master/main.js

**Comment by LaCollins** [comment]
Jquery array method: https://api.jquery.com/jquery.inarray/

**Comment by LaCollins** [comment]
Remove with JQuery: https://stackoverflow.com/questions/3596089/how-to-remove-specific-value-from-array-using-jquery
