### ISSUE TITLE
Display Message

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#17]
## User Story
As a user, when the page loads, I should see messages.

## AC
**Given** A user navigates to your page
**Then** they should see the 5 messages from `data/messages.js`
**And** when they add messages it should add them to the list

## Dev Notes
* in javascripts, create displayMessage folder with displayMessage.js & displayMessage.scss
* message card should have 3 columns 
-- The first will contain the name and time stacked vertically.  Use 'col-3' class to set width
-- The second will contain the message. Use 'col-6' class to set width
-- The third will contain the edit and delete icons in one row & up and down vote buttons in a second row. Use 'col-3' class to set width
* give each card a class `messageCard`
* column 3 button functions will be built in separate tickets
* name, timestamp, and message should all be in p tags
* set a generic message array parameter
* name, timestamp, message, and likes should be pulled from the messages array

* import `data/messages.js` into main.js and assign the `getMessages()` function to a variable
* call the displayMessage function in the init on main.js and pass in the messages array as an argument

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/66880531-eb131d80-ef88-11e9-8a91-3feabd183e9c.png)

**Comment by aclai4067** [comment]
mockup note: we decided not to include 👍 👎 at this time, column three will be only the x and pencil
