### ISSUE TITLE
Wireframe

### ISSUE THREAD

**Issue by aclai4067** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#19]
![image](https://user-images.githubusercontent.com/51382883/66880032-9a9ac080-ef86-11e9-8cc3-b65cd064e915.png)

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/66880004-8787f080-ef86-11e9-88fd-63a3479f58fd.png)
