### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#2]
## User Story
As a user, with sensitive eyes, I should be able to chat using a dark theme.

## AC
**Given** A user navigates to your page
**Then** they should see a checkbox below the input field called "Dark Theme"
**And** they should be able to click this checkbox
**And** when the checkbox is selected the page should show a dark theme with lightly colored text

## Dev Notes
* Use checkbox to toggle classes that trigger different 'scss' styling.
* See below documentation

**Comment by LaCollins** [comment]
https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8
