### ISSUE TITLE
Editing

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#4]
# User Story
As a user, I want the option to edit my message

# A/C
**When** The user clicks the pencil icon
**Then** the linked message will display in the input form at the top of the page
**And** the submit button will be replaced with an update button
**And** when the user makes their change and clicks update or hits enter their message updates

# Dev Notes
* Apply .on('click') listener to all pencil icons
1. Let users edit an existing message. Add an edit button next to the delete button that, when clicked, will take the message and put it back in the message input at the top.
1. Once user edits the message and presses the return key again, the message text in the list should be updated.

**Comment by LaCollins** [comment]
fontawesome pencil: `<i class="fas fa-pencil-alt"></i>`

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/66880923-8d7fd080-ef8a-11e9-893d-8d89adb7ef88.png)
