### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/chatty-group-project-fire-bellied-toads#8]
## User Story
As a user, using all the chatting sites, I always see clean looking timestamps.

**Dirty Timestamp:**  2014-09-08T08:02:17-05:00
**Clean Timestamp:**  September 8, 2014 8:02 PM

## AC
**Given** A user navigates to your page
**Then** they see all the messages
**And**  the messages should have nice looking timestamps

## Dev Notes
* Real JS developers hate dates - they use a magical library called [MomentJS](https://momentjs.com/)
```js
npm install moment --save
```
* Use: `moment().format('llll');` when messages is submitted

**Comment by LaCollins** [comment]
![image](https://user-images.githubusercontent.com/51382883/66880694-a9cf3d80-ef89-11e9-8270-ce8e798e729e.png)

**Comment by LaCollins** [comment]
Moment documentation: https://flaviocopes.com/momentjs/

**Comment by LaCollins** [comment]
👍
